### PR TITLE
Update Typescript functional component

### PR DESCRIPTION
**Pull request by bastiengrignon**

### CODE REVIEW

**Comment by xavierbriole** [comment]
That's cool ! But why removing

`import styles from '../styles.module.css'` ?

**Comment by bastiengrignon** [comment]
I forgot to import it in the index file, You need to include it once in the `src/index.tsx` and everything should work fine

**Comment by xavierbriole** [comment]
Okay great ! Can you confirm it by testing ?
You can launch `yarn run start` in root folder + `yarn run start` in example folder

**Comment by bastiengrignon** [comment]
It's not working 😬 But that's weird because I've never use this kind of syntax and it was working perfectly !
I'll try to figure out why it's not working

**Comment by xavierbriole** [comment]
That would be nice indeed 👍

**Comment by bastiengrignon** [comment]
I don't understand why it's not working ! This should work fine like [this](https://create-react-app.dev/docs/adding-a-stylesheet) with no configuration at all but it's not ...
If you have any idea

**Comment by xavierbriole** [comment]
I think CRA uses a webpack plugin that bundle assets and compile it (not sure)

I'll take a look at it but I don't think it's a priority for the release, maybe a further improvements !

**Pull request closed without merging**
